# Generated by Django 5.1.4 on 2024-12-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('power_usage', models.FloatField(help_text='Power usage in watts')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('light_intensity', models.FloatField(help_text='Light intensity in lumens')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
