# Generated by Django 5.1.4 on 2024-12-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomData', '0002_roomdata_delete_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomdata',
            name='timestamp',
        ),
    ]
